<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #F0F4F8; padding: 40px; margin: 0; }
        .card { max-width: 520px; margin: 0 auto; background: #fff; border-radius: 24px; padding: 48px; box-shadow: 0 10px 30px rgba(0,0,0,0.05); }
        .header { text-align: center; margin-bottom: 32px; }
        .title { color: #132C51; font-size: 28px; font-weight: 800; margin-bottom: 12px; letter-spacing: -0.5px; }
        .subtitle { color: #64748B; font-size: 16px; line-height: 1.5; margin-bottom: 32px; }
        .content-box { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 16px; padding: 24px; margin-bottom: 32px; }
        .content-label { color: #1C427A; font-size: 16px; font-weight: 700; margin-bottom: 8px; }
        .content-value { color: #475569; font-size: 15px; line-height: 1.6; margin-bottom: 16px; }
        .problem-description { color: #475569; font-size: 14px; line-height: 1.6; font-style: italic; background: #fff; padding: 16px; border-radius: 12px; border: 1px solid #E2E8F0; white-space: pre-wrap; }
        .footer { color: #94A3B8; font-size: 12px; margin-top: 40px; text-align: center; line-height: 1.6; }
    </style>
</head>
<body>
    <div class="card">
        <div class="header">
            <div class="title">New Help Request 📩</div>
            <div class="subtitle">
                A new help request has been submitted from the application.
            </div>
        </div>

        <div class="content-box">
            <div class="content-label">Sender Info</div>
            <div class="content-value">
                <strong>Name:</strong> {{ $name }}<br>
                <strong>Email:</strong> <a href="mailto:{{ $email }}" style="color: #1C427A; text-decoration: none;">{{ $email }}</a>
            </div>
            
            <div class="content-label">Problem Description</div>
            <div class="problem-description">{{ $problem }}</div>
        </div>

        <p style="color: #475569; font-size: 15px; line-height: 1.6; text-align: center; margin-bottom: 0;">
            Please review the request and respond to the sender as soon as possible.
        </p>

        <div class="footer">
            This is an automated message generated by {{ config('app.name', 'Tulist') }}.
        </div>
    </div>
</body>
</html>
